### ISSUE TITLE
Site refuses to render with "Ads are blocked" message

### ISSUE THREAD

**Issue by tfmorris** [codeforboston/vaccinatema#10]
![Screen Shot 2021-02-07 at 12 48 45 PM](https://user-images.githubusercontent.com/82178/107154845-14f11000-6943-11eb-8fe5-38a56484b2a0.png)

It appears to be attempting to load https://www.google.com/adsense/domains/caf.js

It doesn't seem like the kind of site which should be either serving ads or tracking people.

**Comment by tfmorris** [comment]
With the ad blocker turned off, it renders, you guessed it, ads!

I guess the simple explanation is that the site has been hacked.

![Screen Shot 2021-02-07 at 1 27 54 PM](https://user-images.githubusercontent.com/82178/107155884-00177b00-6949-11eb-8dcc-d68b704dea49.png)
![Screen Shot 2021-02-07 at 1 28 19 PM](https://user-images.githubusercontent.com/82178/107155891-06a5f280-6949-11eb-94ca-6789b4168785.png)

**Comment by zzany** [comment]
Can you tell us how you reached that link? Would love to reproduce the issue. Thanks!

**Comment by mzagaja** [comment]
Hi Tom,

Thanks for filing this issue. I have not been able to see nor reproduce this. I 

`dig www.vaccinatema.com`

From your terminal?

Also I will note your screenshot shows vaccinatema.org and not vaccinatema.com. I would confirm you are attempting the correct URL.

-Matt

**Comment by tfmorris** [comment]
My browser history definitely has vaccinatema.org. I'm unlikely to have typed it in by hand, but I can't find any page with that link, so perhaps I did, assuming that anything the Code for Boston was advertising for wouldn't be a `.com` TLD. Sorry if it's a false alarm (although having a squatter on the `.org` equivalent probably isn't ideal).

**Comment by tfmorris** [comment]
@hblumberg has identified the likely source of the misdirectoin.

**Comment by mzagaja** [comment]
Fixed in PR, thanks for finding this all!
